import { Router, Request, Response } from 'express';
import { Word } from '../models/Word';
import { optionalAuth, AuthRequest } from '../middleware/auth';

const router = Router();

// Polyfill for fetch if not available
if (typeof fetch === 'undefined') {
  const nodeFetch = require('node-fetch');
  (global as any).fetch = nodeFetch;
}

// Extended translation dictionary - over 300 common words!
const dictionary: { [key: string]: string } = {
  // Greetings & Basic
  'hello': 'שלום',
  'hi': 'היי',
  'goodbye': 'להתראות',
  'bye': 'ביי',
  'please': 'בבקשה',
  'thanks': 'תודה',
  'thank you': 'תודה רבה',
  'sorry': 'סליחה',
  'excuse me': 'סליחה',
  'yes': 'כן',
  'no': 'לא',
  'maybe': 'אולי',
  'ok': 'בסדר',
  'okay': 'בסדר',
  
  // Animals
  'cat': 'חתול',
  'dog': 'כלב',
  'bird': 'ציפור',
  'fish': 'דג',
  'horse': 'סוס',
  'cow': 'פרה',
  'pig': 'חזיר',
  'sheep': 'כבשה',
  'lion': 'אריה',
  'tiger': 'נמר',
  'elephant': 'פיל',
  'monkey': 'קוף',
  'bear': 'דוב',
  'wolf': 'זאב',
  'fox': 'שועל',
  'rabbit': 'ארנב',
  'mouse': 'עכבר',
  'snake': 'נחש',
  'chicken': 'תרנגולת',
  'duck': 'ברווז',
  'butterfly': 'פרפר',
  'bee': 'דבורה',
  'ant': 'נמלה',
  'spider': 'עכביש',
  
  // Family
  'mother': 'אמא',
  'mom': 'אמא',
  'father': 'אבא',
  'dad': 'אבא',
  'parent': 'הורה',
  'parents': 'הורים',
  'brother': 'אח',
  'sister': 'אחות',
  'family': 'משפחה',
  'baby': 'תינוק',
  'boy': 'ילד',
  'girl': 'ילדה',
  'man': 'גבר',
  'woman': 'אישה',
  'child': 'ילד',
  'children': 'ילדים',
  'son': 'בן',
  'daughter': 'בת',
  'husband': 'בעל',
  'wife': 'אישה',
  'grandmother': 'סבתא',
  'grandfather': 'סבא',
  'aunt': 'דודה',
  'uncle': 'דוד',
  'cousin': 'בן דוד',
  
  // Home & Objects
  'house': 'בית',
  'home': 'בית',
  'room': 'חדר',
  'door': 'דלת',
  'window': 'חלון',
  'table': 'שולחן',
  'chair': 'כיסא',
  'bed': 'מיטה',
  'desk': 'שולחן כתיבה',
  'sofa': 'ספה',
  'lamp': 'מנורה',
  'mirror': 'מראה',
  'picture': 'תמונה',
  'clock': 'שעון',
  'television': 'טלוויזיה',
  'tv': 'טלוויזיה',
  'phone': 'טלפון',
  'computer': 'מחשב',
  'keyboard': 'מקלדת',
  'screen': 'מסך',
  'cup': 'כוס',
  'glass': 'כוס',
  'plate': 'צלחת',
  'fork': 'מזלג',
  'knife': 'סכין',
  'spoon': 'כף',
  'bowl': 'קערה',
  'bottle': 'בקבוק',
  'box': 'קופסה',
  'bag': 'תיק',
  'pen': 'עט',
  'pencil': 'עיפרון',
  'book': 'ספר',
  'paper': 'נייר',
  'key': 'מפתח',
  
  // School & Learning
  'school': 'בית ספר',
  'teacher': 'מורה',
  'student': 'תלמיד',
  'class': 'כיתה',
  'lesson': 'שיעור',
  'homework': 'שיעורי בית',
  'exam': 'מבחן',
  'test': 'מבחן',
  'grade': 'ציון',
  'university': 'אוניברסיטה',
  'college': 'מכללה',
  'library': 'ספרייה',
  'math': 'מתמטיקה',
  'science': 'מדעים',
  'history': 'היסטוריה',
  'english': 'אנגלית',
  'language': 'שפה',
  
  // Food & Drinks
  'food': 'אוכל',
  'water': 'מים',
  'bread': 'לחם',
  'milk': 'חלב',
  'cheese': 'גבינה',
  'butter': 'חמאה',
  'egg': 'ביצה',
  'eggs': 'ביצים',
  'meat': 'בשר',
  'rice': 'אורז',
  'pasta': 'פסטה',
  'pizza': 'פיצה',
  'hamburger': 'המבורגר',
  'sandwich': 'כריך',
  'salad': 'סלט',
  'soup': 'מרק',
  'fruit': 'פרי',
  'apple': 'תפוח',
  'banana': 'בננה',
  'orange': 'תפוז',
  'grape': 'ענב',
  'strawberry': 'תות',
  'watermelon': 'אבטיח',
  'tomato': 'עגבנייה',
  'potato': 'תפוח אדמה',
  'carrot': 'גזר',
  'onion': 'בצל',
  'vegetable': 'ירק',
  'sugar': 'סוכר',
  'salt': 'מלח',
  'coffee': 'קפה',
  'tea': 'תה',
  'juice': 'מיץ',
  'cake': 'עוגה',
  'cookie': 'עוגייה',
  'chocolate': 'שוקולד',
  'ice cream': 'גלידה',
  
  // Nature & Weather
  'sun': 'שמש',
  'moon': 'ירח',
  'star': 'כוכב',
  'sky': 'שמיים',
  'cloud': 'ענן',
  'rain': 'גשם',
  'snow': 'שלג',
  'wind': 'רוח',
  'storm': 'סערה',
  'weather': 'מזג אוויר',
  'tree': 'עץ',
  'flower': 'פרח',
  'grass': 'דשא',
  'plant': 'צמח',
  'garden': 'גן',
  'forest': 'יער',
  'mountain': 'הר',
  'hill': 'גבעה',
  'river': 'נהר',
  'lake': 'אגם',
  'sea': 'ים',
  'ocean': 'אוקיינוס',
  'beach': 'חוף',
  'sand': 'חול',
  'rock': 'סלע',
  'stone': 'אבן',
  'fire': 'אש',
  'earth': 'אדמה',
  'world': 'עולם',
  
  // Colors
  'color': 'צבע',
  'red': 'אדום',
  'blue': 'כחול',
  'green': 'ירוק',
  'yellow': 'צהוב',
  'black': 'שחור',
  'white': 'לבן',
  'purple': 'סגול',
  'pink': 'ורוד',
  'brown': 'חום',
  'gray': 'אפור',
  'grey': 'אפור',
  'gold': 'זהב',
  'silver': 'כסף',
  
  // Numbers
  'zero': 'אפס',
  'one': 'אחד',
  'two': 'שניים',
  'three': 'שלושה',
  'four': 'ארבעה',
  'five': 'חמישה',
  'six': 'שישה',
  'seven': 'שבעה',
  'eight': 'שמונה',
  'nine': 'תשעה',
  'ten': 'עשרה',
  'eleven': 'אחד עשר',
  'twelve': 'שנים עשר',
  'twenty': 'עשרים',
  'thirty': 'שלושים',
  'forty': 'ארבעים',
  'fifty': 'חמישים',
  'hundred': 'מאה',
  'thousand': 'אלף',
  'million': 'מיליון',
  'first': 'ראשון',
  'third': 'שלישי',
  'last': 'אחרון',
  
  // Time
  'time': 'זמן',
  'hour': 'שעה',
  'minute': 'דקה',
  'second': 'שנייה',
  'day': 'יום',
  'night': 'לילה',
  'morning': 'בוקר',
  'afternoon': 'אחר הצהריים',
  'evening': 'ערב',
  'week': 'שבוע',
  'month': 'חודש',
  'year': 'שנה',
  'today': 'היום',
  'tomorrow': 'מחר',
  'yesterday': 'אתמול',
  'now': 'עכשיו',
  'later': 'אחר כך',
  'soon': 'בקרוב',
  'always': 'תמיד',
  'never': 'לעולם לא',
  'sometimes': 'לפעמים',
  'monday': 'יום שני',
  'tuesday': 'יום שלישי',
  'wednesday': 'יום רביעי',
  'thursday': 'יום חמישי',
  'friday': 'יום שישי',
  'saturday': 'שבת',
  'sunday': 'יום ראשון',
  
  // Adjectives
  'good': 'טוב',
  'bad': 'רע',
  'big': 'גדול',
  'small': 'קטן',
  'large': 'גדול',
  'little': 'קטן',
  'long': 'ארוך',
  'short': 'קצר',
  'tall': 'גבוה',
  'high': 'גבוה',
  'low': 'נמוך',
  'wide': 'רחב',
  'narrow': 'צר',
  'thick': 'עבה',
  'thin': 'דק',
  'heavy': 'כבד',
  'hard': 'קשה',
  'soft': 'רך',
  'happy': 'שמח',
  'sad': 'עצוב',
  'angry': 'כועס',
  'tired': 'עייף',
  'hungry': 'רעב',
  'thirsty': 'צמא',
  'beautiful': 'יפה',
  'pretty': 'יפה',
  'ugly': 'מכוער',
  'nice': 'נחמד',
  'kind': 'אדיב',
  'mean': 'רשע',
  'smart': 'חכם',
  'stupid': 'טיפש',
  'clever': 'חכם',
  'funny': 'מצחיק',
  'interesting': 'מעניין',
  'boring': 'משעמם',
  'hot': 'חם',
  'cold': 'קר',
  'warm': 'חמים',
  'cool': 'קריר',
  'wet': 'רטוב',
  'dry': 'יבש',
  'dirty': 'מלוכלך',
  'new': 'חדש',
  'old': 'ישן',
  'young': 'צעיר',
  'fast': 'מהיר',
  'slow': 'איטי',
  'quick': 'מהיר',
  'strong': 'חזק',
  'weak': 'חלש',
  'full': 'מלא',
  'empty': 'ריק',
  'right': 'נכון',
  'wrong': 'שגוי',
  'true': 'נכון',
  'false': 'שקר',
  'easy': 'קל',
  'difficult': 'קשה',
  'simple': 'פשוט',
  'rich': 'עשיר',
  'poor': 'עני',
  'expensive': 'יקר',
  'cheap': 'זול',
  'free': 'חינם',
  
  // Verbs (infinitive)
  'be': 'להיות',
  'have': 'להחזיק',
  'do': 'לעשות',
  'make': 'לעשות',
  'go': 'ללכת',
  'come': 'לבוא',
  'take': 'לקחת',
  'get': 'לקבל',
  'give': 'לתת',
  'see': 'לראות',
  'look': 'להסתכל',
  'watch': 'לצפות',
  'hear': 'לשמוע',
  'listen': 'להקשיב',
  'speak': 'לדבר',
  'talk': 'לדבר',
  'say': 'לומר',
  'tell': 'לספר',
  'ask': 'לשאול',
  'answer': 'לענות',
  'eat': 'לאכול',
  'drink': 'לשתות',
  'sleep': 'לישון',
  'wake': 'להתעורר',
  'sit': 'לשבת',
  'stand': 'לעמוד',
  'walk': 'ללכת',
  'run': 'לרוץ',
  'jump': 'לקפוץ',
  'swim': 'לשחות',
  'fly': 'לעוף',
  'drive': 'לנהוג',
  'ride': 'לרכוב',
  'play': 'לשחק',
  'work': 'לעבוד',
  'study': 'ללמוד',
  'learn': 'ללמוד',
  'teach': 'ללמד',
  'read': 'לקרוא',
  'write': 'לכתוב',
  'draw': 'לצייר',
  'sing': 'לשיר',
  'dance': 'לרקוד',
  'buy': 'לקנות',
  'sell': 'למכור',
  'pay': 'לשלם',
  'open': 'לפתוח',
  'close': 'לסגור',
  'start': 'להתחיל',
  'begin': 'להתחיל',
  'finish': 'לסיים',
  'end': 'לסיים',
  'stop': 'לעצור',
  'wait': 'לחכות',
  'help': 'לעזור',
  'need': 'להזדקק',
  'want': 'לרצות',
  'like': 'לאהוב',
  'love': 'לאהוב',
  'hate': 'לשנוא',
  'know': 'לדעת',
  'understand': 'להבין',
  'think': 'לחשוב',
  'believe': 'להאמין',
  'remember': 'לזכור',
  'forget': 'לשכוח',
  'find': 'למצוא',
  'lose': 'לאבד',
  'bring': 'להביא',
  'carry': 'לשאת',
  'put': 'לשים',
  'keep': 'לשמור',
  'break': 'לשבור',
  'fix': 'לתקן',
  'clean': 'לנקות',
  'wash': 'לשטוף',
  'cook': 'לבשל',
  'cut': 'לחתוך',
  'try': 'לנסות',
  'use': 'להשתמש',
  'show': 'להראות',
  'feel': 'להרגיש',
  'touch': 'לגעת',
  'smell': 'להריח',
  'taste': 'לטעום',
  
  // Places
  'place': 'מקום',
  'city': 'עיר',
  'town': 'עיירה',
  'village': 'כפר',
  'country': 'מדינה',
  'street': 'רחוב',
  'road': 'כביש',
  'park': 'פארק',
  'store': 'חנות',
  'shop': 'חנות',
  'market': 'שוק',
  'supermarket': 'סופרמרקט',
  'restaurant': 'מסעדה',
  'cafe': 'בית קפה',
  'hotel': 'מלון',
  'hospital': 'בית חולים',
  'bank': 'בנק',
  'post office': 'דואר',
  'airport': 'שדה תעופה',
  'station': 'תחנה',
  'museum': 'מוזיאון',
  'theater': 'תיאטרון',
  'cinema': 'קולנוע',
  'church': 'כנסייה',
  'mosque': 'מסגד',
  'temple': 'מקדש',
  
  // Transport
  'car': 'מכונית',
  'bus': 'אוטובוס',
  'train': 'רכבת',
  'plane': 'מטוס',
  'airplane': 'מטוס',
  'ship': 'אונייה',
  'boat': 'סירה',
  'bicycle': 'אופניים',
  'bike': 'אופניים',
  'motorcycle': 'אופנוע',
  'truck': 'משאית',
  'taxi': 'מונית',
  
  // Body parts
  'body': 'גוף',
  'head': 'ראש',
  'face': 'פנים',
  'eye': 'עין',
  'eyes': 'עיניים',
  'ear': 'אוזן',
  'nose': 'אף',
  'mouth': 'פה',
  'tooth': 'שן',
  'teeth': 'שיניים',
  'tongue': 'לשון',
  'lip': 'שפה',
  'hair': 'שיער',
  'neck': 'צוואר',
  'shoulder': 'כתף',
  'arm': 'זרוע',
  'hand': 'יד',
  'finger': 'אצבע',
  'chest': 'חזה',
  'back': 'גב',
  'stomach': 'בטן',
  'leg': 'רגל',
  'knee': 'ברך',
  'foot': 'כף רגל',
  'feet': 'כפות רגליים',
  'toe': 'אצבע רגל',
  'heart': 'לב',
  'blood': 'דם',
  'bone': 'עצם',
  'skin': 'עור',
  
  // Misc
  'thing': 'דבר',
  'person': 'אדם',
  'people': 'אנשים',
  'life': 'חיים',
  'death': 'מוות',
  'friend': 'חבר',
  'enemy': 'אויב',
  'money': 'כסף',
  'job': 'עבודה',
  'name': 'שם',
  'age': 'גיל',
  'number': 'מספר',
  'word': 'מילה',
  'question': 'שאלה',
  'problem': 'בעיה',
  'idea': 'רעיון',
  'way': 'דרך',
  'example': 'דוגמה',
  'story': 'סיפור',
  'game': 'משחק',
  'music': 'מוזיקה',
  'song': 'שיר',
  'art': 'אמנות',
  'sport': 'ספורט',
  'ball': 'כדור',
  'toy': 'צעצוע',
  'gift': 'מתנה',
  'present': 'מתנה',
  'party': 'מסיבה',
  'birthday': 'יום הולדת',
  'holiday': 'חג',
  'vacation': 'חופשה',
  'trip': 'טיול',
  'photo': 'תמונה',
  'movie': 'סרט',
  'film': 'סרט',
  'news': 'חדשות',
  'information': 'מידע',
  'message': 'הודעה',
  'letter': 'מכתב',
  'email': 'אימייל',
  'internet': 'אינטרנט',
  'website': 'אתר',
  'page': 'עמוד',
  'sound': 'צליל',
  'voice': 'קול',
  'noise': 'רעש',
  'dark': 'חושך',
  'shadow': 'צל',
  'peace': 'שלום',
  'war': 'מלחמה',
  'danger': 'סכנה',
  'safety': 'בטיחות',
  'health': 'בריאות',
  'sick': 'חולה',
  'medicine': 'תרופה',
  'doctor': 'רופא',
  'nurse': 'אחות',
  'law': 'חוק',
  'rule': 'כלל',
  'government': 'ממשלה',
  'president': 'נשיא',
  'king': 'מלך',
  'queen': 'מלכה',
  'prince': 'נסיך',
  'princess': 'נסיכה',
};

// Translate endpoint - now checks user's saved words first!
router.post('/translate', optionalAuth, async (req: AuthRequest, res: Response) => {
  try {
    const { text } = req.body;
    
    if (!text || typeof text !== 'string') {
      return res.status(400).json({ error: 'Text is required' });
    }

    const lowerText = text.toLowerCase().trim();
    
    // FIRST: Check if user already has this word saved in their collection
    if (req.userId) {
      try {
        const existingWord = await Word.findOne({ 
          userId: req.userId, 
          english: { $regex: new RegExp(`^${lowerText}$`, 'i') } 
        });
        
        if (existingWord && existingWord.hebrew) {
          console.log('Found in user collection:', lowerText);
          return res.json({ translation: existingWord.hebrew, source: 'user-collection' });
        }
      } catch (dbError) {
        console.log('DB lookup error (continuing):', dbError);
      }
    }
    
    // SECOND: Check local dictionary
    if (dictionary[lowerText]) {
      return res.json({ translation: dictionary[lowerText], source: 'local' });
    }

    // THIRD: Try LibreTranslate API (free service)
    try {
      const response = await fetch('https://libretranslate.com/translate', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          q: text,
          source: 'en',
          target: 'he',
          format: 'text'
        })
      });

      const data: any = await response.json();
      if (data.translatedText) {
        return res.json({ translation: data.translatedText, source: 'api' });
      }
    } catch (apiError) {
      console.log('External API not available, dictionary only');
    }

    // If no translation found
    return res.status(404).json({ 
      error: 'Translation not found',
      message: 'לא נמצא תרגום עבור מילה זו. אנא הזן את התרגום ידנית.'
    });

  } catch (error) {
    console.error('Translation error:', error);
    res.status(500).json({ error: 'Translation service error' });
  }
});

export default router;
